CREATE LOGIN [etl] 
	WITH PASSWORD=N'5i5HZ9zeuwn3XqXzDTTBBg5W2whU9G9ScbjObEJgE6o=', 
	DEFAULT_DATABASE=[AdventureWorks2022], 
	DEFAULT_LANGUAGE=[us_english], 
	CHECK_EXPIRATION=OFF, 
	CHECK_POLICY=OFF;

ALTER LOGIN [etl] 
	DISABLE;