SELECT [city_name]
      ,[state_province_code]
      ,[state_province_name]
      ,[country_region_code]
      ,[country_region_name]
      ,[region]
      ,[sub_region]
      ,[latitude]
      ,[longitude]
      ,[rowguid]
      ,[modified_date]
  FROM [Person].[Location]