GRANT USAGE ON SCHEMA "public" TO etl_user;
GRANT USAGE ON SCHEMA "people" TO etl_user;
GRANT USAGE ON SCHEMA "production" TO etl_user;
GRANT USAGE ON SCHEMA "sales" TO etl_user;
GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA "people" TO etl_user;
GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA "production" TO etl_user;
GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA "sales" TO etl_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" GRANT INSERT, UPDATE, DELETE, SELECT ON TABLES TO etl_user;